version: "2.3"
services:

  gazebo:
    image: ${DOCKER_IMAGE:-arm_gazebo}
    container_name: armgazebo
    runtime: nvidia
    tty: true
    ipc: host
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/robot/.Xauthority
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${ARM_GAZEBO_DIR}:/home/robot/src/arm_gazebo
    working_dir: /home/robot/
    entrypoint:
    - bash
    - -ci 
    - "cd /home/robot/src/arm_gazebo/bin && ./init_sim.bash"


