version: "2.3"
services:

  xserver:
    image: devrt/xserver
    container_name: xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  gazebo:
    image: ${DOCKER_IMAGE:-arm_gazebo}
    container_name: armgazebo
    tty: true
    ipc: host
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    volumes_from:
      - xserver
    depends_on:
      - xserver
    volumes:
      - ${ARM_GAZEBO_DIR}:/home/robot/src/arm_gazebo
    working_dir: /home/robot/
    entrypoint:
    - bash
    - -ci 
    - "cd /home/robot/src/arm_gazebo/bin && ./init_sim.bash"



